### ISSUE TITLE
Getting started steps fail at npm install on Windows

### ISSUE THREAD

**Issue by jakenuts** [algolia/algolia-ui-kit#31]
50 info AlgoliasearchUIKit@1.0.0 Failed to exec postinstall script
51 error AlgoliasearchUIKit@1.0.0 postinstall: `mkdir -p ./dist`
51 error Exit status 1
52 error Failed at the AlgoliasearchUIKit@1.0.0 postinstall script.
52 error This is most likely a problem with the AlgoliasearchUIKit package,
52 error not with npm itself.
52 error Tell the author that this fails on your system:
52 error     mkdir -p ./dist

Changing step to mkdir dist works, but then the steps fail at npm run build:js

**Comment by bobylito** [comment]
Thanks for the @jakenuts for the issue. I'll work on a fix this week. In the mean time you could try with cygwin (I know this is not the ideal setup ;) ). I'll keep you in touch.
