### ISSUE TITLE
InstantSearch.js

### ISSUE THREAD

**Issue by bobylito** [algolia/algolia-ui-kit#34]
Replace the dom interface by a programmatic interface to the UI-Kit and rename the project to instantsearch.js
# Motivation

The  current implementation is very easy to use but once you hit one of its limits, the path to customisation is very steep. In order to reduce the gap between ease of use and extensibility, we need to rethink the API and at least provide a programmatic way to interact with the current architecture with hooks, data filters/transformers and much more template possibilities.
# Expose the current flow of initialisation

Right now, the initialisation flow is as follow (this is now done in a IIFE):
1. Read the DOM and create a parameters object
2. Helper instanciation and event listener setup
3. First query (that will then trigger the first rendering)

The third step triggers the feedback flow between user input and new renderings.

From there, we could easily expose the process from the second step as function or an object. The function would be simpler but the object could let us add hooks to our API. 

The API could look like (similiar to the intermediate config currently used) : 

``` javascript
instantsearch( {
  applicationID : "",
  apiKey : "",
  searchbox : {
    nodeSelector : "#my-search-box",
    placeholder : "My super search box"
  },
  hits : {
    nodeSelector : "#hits",
    resultTemplate : "<div class='results'>{name} - {followers}</div>"
  }
} ); 
```

This API differs from the current implementation with the use of selector instead of DomElements.
# Creating new widgets

Each block represent a specific widget configuration. This version would be very bound to the existing scope of supported widget. One way we could avoid that would be to have widget represented with real object responding to a wider contract that could also contain the rendering of the widget itself :

``` javascript
var search = instantSearch( {
  applicationID : "",
  apiKey : ""
} );

search.addWidget(searchBox({
  node-selector : "#my-search-box"
}));
```

searchbox instanciate a new object that follows the contract : 

``` javascript
{
  render : function(){ /* changes the dom */ }, 
}
```

The render function could use any sort of library. And we could also be able to use plain objects (for singleton and rapid prototyping)
# Transforming data

The object returned by the widget could also bear some hook function from the lifecycle. For example we could have a `transformData` function that transform the data in a new object. As long as this function exists, it will be called before the rendering and its result will be passed to the render function.

``` javascript
{
  render : function( data ){
    React.render( <div>{data.name} - {data.followers}</div> );
  },
  transformData : function( rawData ){
    return {
      name : rawData.name.capitalize(),
      followers : rawData.followers
    };
  }
}
```
# Other ideas
- path to data

**Comment by bobylito** [comment]
WIP :)

**Comment by vvo** [comment]
Coool!

**Comment by redox** [comment]
:+1: I want to see it live in an MVP !

**Comment by bobylito** [comment]
On it!

**Comment by vvo** [comment]
What about the autocomplete widget? Will we have one?

Since a good proportion of our clients like to have autocomplete menu then instant search, should we integrate the autocomplete widget in the instantsearch.js lib?

Otherwise, clients would again have to add 3 `<script>`s on the first page, then on the instant search page they would be able to use instantsearch.js.

**Comment by vvo** [comment]
Also @bobylito it could be great to iterate on the API level of this module before we work on the code itself. What do you think? We could have multiple issues representing each widget and each widget necessary API/options.

**Comment by vvo** [comment]
> instantsearch( {
>   applicationID : "",
>   apiKey : "",
>   searchbox : {
>     nodeSelector : "#my-search-box",
>     placeholder : "My super search box"
>   },
>   hits : {
>     nodeSelector : "#hits",
>     resultTemplate : "<div class='results'>{name} - {followers}</div>"
>   }
> } );

Because the instantiation options will go crazy, I would prefer to use something like:

``` js
var search = instantSearch(applicationId, apiKey, opts);

var searchBox = search.addWidget('search-box', opts);
var priceSlider = search.addWidget('slider', opts);
var categories = search.addWidget('hierarchical-menu', opts);
var manufacturer = search.addWidget('multiple-choices', opts);
```

What do you think?

**Comment by redox** [comment]
> should we integrate the autocomplete widget in the instantsearch.js lib

I think it's gonna be too complex, let's start with 2 distinct components.

**Comment by redox** [comment]
> What do you think?

:+1:

**Comment by bobylito** [comment]
Ok the issue was not clear enough. I agree with you @vvo, but I would go a step further. Keys as you propose only let you set widgets that the instantsearch.js knows. Whereas we can have a specific contract, formalized in constructors, like the SearchBox and the Results. But in the end, the instant search would only need objects that implements render and the optionnal hooks.

``` js
var search = instantSearch(applicationId, apiKey );

search.addWidget( searchBox( opts1 ) );
search.addWidget( slider( opts2 ) );
```

Here the opts1 and opts2 would contain the node selector into which the component should do the rendering and the different specific options for the widget.

To give you an example of a custom widget done on the fly : 

``` js
var search = instantSearch(applicationId, apiKey );

search.addWidget( {
  render : function( searchParameters, results ) { $( "results" ).html( template( results ) ); } 
} );
```

**Comment by redox** [comment]
I'm almost convinced we should not make React.js visible (like the `render` method).

Also I wasn't sure you wanted to have the whole/final API now, so let me show you what I had in mind:

``` html
<input type="text" id="search-input" />

<!-- [...] -->

<div class="row">
  <div class="col-sm-3" id="facets"></div>
  <div class="col-sm-9">
    <div id="stats"></div>
    <div id="hits"></div>
    <div id="pagination"></div>
  </div>
</div>

<!-- [...] -->

<script>
instantsearch("ApplicationID", "SearchOnlyAPIKey", {
  index: 'YourIndex',
  input: {
    selector: "#search-input",
    placeholder: "Search for products by name, categories, description..."
  },
  hits: {
    selector: "#hits",
    onHit: function(hit, content) { return hit; }, // optional function to override/enrich a hit before display
    template: /* function(hit) {} or string */,
    sortOrders: [
      { label: "Relevance", index: "YourIndex" },
      { label: "Highest price", index: "YourIndex_price_desc" },
      { label: "Lowest price", index: "YourIndex_price_asc" }
    ]
  },
  pagination: {
     selector: "#pagination",
     nbHitsPerPage: 12
  },
  facets: {
    selector: "#facets",
    onFacets: function(facets, content) { return facets; },  // optional function to override/enrich a facet before display
    configuration: [
      {
        attribute: 'category',
        sortBy: 'count',
        onFacet: function(facet, content) { return facet; } // optional function to override/enrich a facet value before display
      },
      {
        attribute: 'price',
        type: 'slider',
        onFacet: function(facet, content) { return facet; } // optional function to override/enrich a facet value before display
      },
      {
        attribute: 'price',
        type: 'disjunctive',
        sortBy: 'value',
        onFacet: function(facet, content) { return facet; } // optional function to override/enrich a facet value before display
      }
    ]
  },
  stats: {
    selector: "#stats",
    displayProcessingTime: true
  }
});
</script>
```

I would not allow any templating for the facets, the sorts and the pagination for now: only customizable with CSS.

I'm not sure about the `on{Hit,Facet,Facets}` naming, but couldn't find something smarter (didn't like the `filter/map` options).

**Comment by bobylito** [comment]
> I'm almost convinced we should not make React.js visible (like the render method).

Agreed, this is just convention, not an exposition of the React API. That's true that the current implementation of instantsearch.js is influenced by this API, it does not make React mandatory. For example, this is an example of **custom code** with jQuery rendering and template (quick and dirty) : 

``` javascript
var search = instantSearch(applicationId, apiKey ); 
search.addWidget( {
   render : function( searchParameters, results ) { $( "results" ).html( template( results ) ); } 
 } );
```

The idea is to provide the components needed and let people choose without restricting the use to a particular tool. Truth is that making the widget definition very clear will make the implementation for us much more easily. And we don't need to expose or document the custom API right away.

As for your example, the parameters for each widget are great and definitely what we would need for such components. The only problem is that it relies on keys previously known by the instantsearch, which will limit further extensions and cutomization. That's why I propose a factory based approach. Your example in this mindset would be : 

``` javascript
var search = instantsearch("ApplicationID", "SearchOnlyAPIKey", {
  index: 'YourIndex'
});

search.addWidget(input({
  selector: "#search-input",
  placeholder: "Search for products by name, categories, description..."
}));

search.addWidget(hits({
  selector: "#hits",
  onHit: function(hit, content) { return hit; }, // optional function to override/enrich a hit before display
  template: /* function(hit) {} or string */,
  sortOrders: [
    { label: "Relevance", index: "YourIndex" },
    { label: "Highest price", index: "YourIndex_price_desc" },
    { label: "Lowest price", index: "YourIndex_price_asc" }
  ]
}));

search.addWidget(pagination({
  selector: "#pagination",
  nbHitsPerPage: 12
}));

search.addWidget(facets( {
  selector: "#facets",
  onFacets: function(facets, content) { return facets; },  // optional function to override/enrich a facet before display
  configuration: [
    {
      attribute: 'category',
      sortBy: 'count',
      onFacet: function(facet, content) { return facet; } // optional function to override/enrich a facet value before display
    },
    {
      attribute: 'price',
      type: 'slider',
      onFacet: function(facet, content) { return facet; } // optional function to override/enrich a facet value before display
    },
    {
      attribute: 'price',
      type: 'disjunctive',
      sortBy: 'value',
      onFacet: function(facet, content) { return facet; } // optional function to override/enrich a facet value before display
    }
  ]
}));

search.addWidget(stats({
  selector: "#stats",
  displayProcessingTime: true
}));
```

The functions `hits`, `input`, `pagination`,  `facets` and `stats` will create objects that follow a specific contract based on the widget lifecycle (and may contain a render or update function with hooks and everything). But this contract is not to exposed directly in the widget factories parameters (as per the last example).

**Comment by vvo** [comment]
@bobylito 

> Keys as you propose only let you set widgets that the instantsearch.js knows

Yes and I feel that we should first aim at answering the most common need which will be using the widgets we provide.

But that does not restricts us from providing an API that will allow people to create their own widgets, based on the helper events and state.

@redox 

> I'm almost convinced we should not make React.js visible (like the render method).

Yes we should not make React.js visible in our API.

@bobylito, @redox:
From our current discussion and API proposals here are my thoughts:
- big configuration object does not scale well, we should avoid it. Hard to read.
- big configuration object does not allows you to provide widget instances api:
  
  ```
    categories.select('fruits');
    categories.hide();
    categories.remove();
    price.set(1000, 3000)`
  ```
  
  Why would we want this?
  
  Because setting the value of the slider or selecting a checkbox with DOM will be hacky
  and given our own implementation may even not work.
- I would not talk about faceting or disjunctive faceting.
  
  **As a end user** what I want to do is to _"add a checkbox list on the 'manufacturer' attribute"_ (user API POV).
  
  If I have to transcribe this need to _"add a disjunctive facet on manufacturer attribute in the facets array parameter"_ (implementation API POV) then I will be a bit lost and not very far from using the helper API.
  
  It will take me some good time (carefully read the docs, remember what a disjunctive facet is etc..)
  and I would not very happy since I tought this was a high level API.
- I do not get well the `search.addWidget(input({...});`:
  1. Where does the 'input' function comes from?
  2. What does it brings versus `search.addWidget('input', opts)` (aside from custom widgets you might want to create)?
  3. I feel I would really prefer to use the `search.addWidget('input', opts)` form, less moving parts.
- I would provide both `#selectors` and `DOMElement` as `container` parameter instead of `selector`.
  So we handle right now cases where you would want to either build your DOM programmaticaly.

Let me propose another API:

``` js
// same instantiation as helper and client
var search = instantSearch(applicationId, apiKey, {
  // instant search global parameters
  indexName: 'demo', 
  syncToUrl: true,
  hitsPerPage: 20
});

var searchBox = search.add('search-box', {
  container: '#selector' // or DOMElement.
});

// `container` could even be optional.
// You would then have to attach your searchBox yourself,
// when you want (example usage: dynamically created DOM)
// document.querySelector('#async-created-dom-node').appendChild(searchBox.DOMElement)

var hits = search.add('hits', {
  container: '#hits', // or container: DOMElement, useful when programatically building a dom (like `$('<div id="hits">'`)
  template: function(hit) {}, // or string, if string, I think we should default to hogan.js templating, again for ease of use of most users
  onHit: function(hit) {} // even if that's redundant with `template: function(hit) {}`, still very useful
});

// different widget for sorting hits, so you position it where you want, maybe in another column from the hits
var order = search.add('sort-hits', {
  container: '#sort-hits',
  sortBy: [
    {label: 'Relevance', indexName: 'YourIndex'}, // first one is default, selected
    {label: "Highest price", indexName: 'YourIndex_price_desc'},
    {label: "Lowest price", indexName: 'YourIndex_price_asc'}
  ]
});

// as every widget is now accessible by an object, you can do:
// order.select('Highest price');
// search.refresh();
// without having to do weird DOM manipulations

var priceSlider = search.add('slider', opts);
var categories = search.add('hierarchical-menu', {
  attributes: ['categories.lvl0', 'categories.lvl1'],
  container: '#categories', // or DOMElement
  template: function(category) {} // or string
});

var manufacturer = search.add('multiple-choice', { // may find a better name for this one
  attribute: 'manufacturer',
  container: '#selector', // or DOMElement
  template: function(choice) {}, // or string. default to '<input type=checkbox /> {{value}}'
});
```

What do you think?

**Comment by bobylito** [comment]
> I do not get well the search.addWidget(input({...});:
>   * Where does the 'input' function comes from?

>   * What does it brings versus search.addWidget('input', opts) (aside from custom widgets you might want to create)?
>   * I feel I would really prefer to use the search.addWidget('input', opts) form, less moving parts.

**Comment by bobylito** [comment]
> @bobylito
> 
> > Keys as you propose only let you set widgets that the instantsearch.js knows
> 
> Yes and I feel that we should first aim at answering the most common need which will be using the widgets we provide.

What if we already have the solution for doing both?

> But that does not restricts us from providing an API that will allow people to create their own widgets, based on the helper events and state.

Making an API for extending is harder than making an API that is by design extensible.

> @redox
> 
> > I'm almost convinced we should not make React.js visible (like the render method).
> 
> Yes we should not make React.js visible in our API.

Agreed (see previous comment)

> @bobylito, @redox:
> From our current discussion and API proposals here are my thoughts:
> 
> big configuration object does not scale well, we should avoid it. Hard to read.
> big configuration object does not allows you to provide widget instances api:
> 
>   categories.select('fruits');
>   categories.hide();
>   categories.remove();
>   price.set(1000, 3000)`
> Why would we want this?
> 
> Because setting the value of the slider or selecting a checkbox with DOM will be hacky
> and given our own implementation may even not work.

Interesting perspectives! I like that. Even though I don't think that we need that right now, I think the previous API (especially the fully declarative one) would not make it possible. Would it be like :

``` javascript
var inputInstance = search.addObject( 'input', {} );
// inputInstance being of type WidgetInstance or InputInstance
// For the sake of talking about the approach I'm defending ;) It could work the same
var inputInstance2 = search.addObject(input({}));
```

> I would not talk about faceting or disjunctive faceting.
> 
> As a end user what I want to do is to "add a checkbox list on the 'manufacturer' attribute" (user API POV).
> 
> If I have to transcribe this need to "add a disjunctive facet on manufacturer attribute in the facets array parameter" (implementation API POV) then I will be a bit lost and not very far from using the helper API.
> 
> It will take me some good time (carefully read the docs, remember what a disjunctive facet is etc..)
> and I would not very happy since I tought this was a high level API.

I also think that from a UI POV it's better to express UI terms!

> I do not get well the search.addWidget(input({...});:
> - Where does the 'input' function comes from?

In a module based context, it would obviously come a separate module. In basic browser context, it could be namespaced and then aliased.

> - What does it brings versus search.addWidget('input', opts) (aside from custom widgets you might want to create)?

It is easier to reason about and enumerate explicitly represented objects and their constructors than keys. Also it is also easier to document because there will be lots of parameters.

> - I feel I would really prefer to use the search.addWidget('input', opts) form, less moving parts.

In that you are right, having a more restrictive API is more coercive. But it also makes extra hard dependencies on different parts of the code.

> I would provide both #selectors and DOMElement as container parameter instead of selector. So we handle right now cases where you would want to either build your DOM programmaticaly.

Sounds good to me!

**Comment by redox** [comment]
We'll need to iterate on the wording (especially for the facets), but you guys are right about the "big" configuration object it doesn't scale well -> the `add{,Widget}` looks good to me.

**Comment by vvo** [comment]
So we discussed this with @bobylito @pixelastic this morning.

We agreed that the proposed API from @bobylito would be the best for all use cases:

``` js
  var instant = instantSearch(appId, apiKey, opts);
  instant.addWidget(instantSearch.widgets.searchBox({
    container: '#search-box'
  }));
```

To give you an idea, the `searchBox` widget could look like this:

algolia/instantsearch.js-searchBox/index.js:

``` js
module.exports = function searchBox(opts) {

  return function(content, state, helper) {
    // manipulate content, use provided `opts` and fill the `opts.container` with the html
    // here you can use REACT, jquery etc.. we do not care
  }
}
```

Every module could be written, developed and tested separately, since it's really input (opts, content, helper) => output (DOM result). The `instantSearch` module is only some glue and a namespace for "core" widgets.

We should provide all the necessary "core" widgets, examples:
- algolia/instantsearch.js-searchBox
- algolia/instantsearch.js-hits
- algolia/instantsearch.js-multipleChoice (still not the right name for disjunctiveFacets :)
- algolia/instantsearch.js-menu
- algolia/instantsearch.js-hierarchicalMenu
- algolia/instantsearch.js-slider
- algolia/instantsearch.js-stats
- algolia/instantsearch.js-sortOrder
- algolia/instantsearch.js-pagination
- ..?

Next steps we could do (team work):
- [ ] create algolia/instantsearch.js
- [ ] create algolia/instantsearch.js-searchBox
- [ ] create algolia/instantsearch.js-hits
- [ ] create a working jsfiddle using the searchbox and hits to create a simple instant demo
- [ ] show off and validate with more people, then go widget-frenzy

what do you think?

**Comment by pixelastic** [comment]
I like the way @vvo split it. Each widget is a simple function taking `content`, `state` and `helper` and we can do whatever we want inside.

This will let us work in parallell on different widgets, while still allowing for custom code for clients or demos. As each widget will have a small UI scope, it is no big deal to start from scratch if we ever need something special. And we can all work in parallel on creating the official widgets.

**Comment by redox** [comment]
LGTM :+1: 

And why does the `render` function take the `state` **and** the `helper` in arguments?

**Comment by vvo** [comment]
> And why does the render function take the state and the helper in arguments?

As for the `state` param: I am not sure of the use case. cc @bobylito?

As for the `helper` param: it's needed since when you click on the slider, you will refine the search by using an helper method. (Or when you click on a checkbox/hierarchical facet link etc..)

Better?

**Comment by redox** [comment]
Yes my concern was why having both; I think the helper is enough.

**Comment by vvo** [comment]
Ok, maybe we do not need the `content, state, helper`, `content, helper` will be sufficient.

The most used object will be the content and helper, if we have to access the state by `helper.state` then maybe that's enough

**Comment by bobylito** [comment]
> As for the state param: I am not sure of the use case. cc @bobylito?

Because we need the state for some components like the slider (current values with disjunctive facetting). We can't rely on the state from the helper as it may not be the one associated with the response.

**Comment by bobylito** [comment]
LGTM @vvo, let's rock it that with an initial proto :)

**Comment by bobylito** [comment]
https://github.com/algolia/instantsearch.js :boom:

**Comment by vvo** [comment]
Latest API looks like this:

``` js
module.exports = function searchBox(opts) {

  return {
    configure: function() {
      // augment helper configuration
      return {
        facets: ['cool']
      }
    },
    render: function(content, state, helper) {

    }
  }
}
```

So we switch from a single `render` function based API to an object based since we need to configure the helper before rendering (adding facets etc..).

**Comment by vvo** [comment]
Development and API design is now in https://github.com/algolia/instantsearch.js
