### ISSUE TITLE
Index selector

### ISSUE THREAD

**Issue by bobylito** [algolia/algolia-ui-kit#4]
Index selector is a component to use when different ranking apply and the user wants to update which index is targeted

**Comment by redox** [comment]
Do you already have an idea how to to use it from the DOM?

**Comment by bobylito** [comment]
I started to use the option / select combination to represent the combination of selectable items. But it does not fit the rendering as you can't replace the content of a select with div's. I'm now with a combination of div / option, but this is clearly weird in terms of html semantics (will push right away). Otherwise I'm thinking maybe using lists, or just imbricated divs...

**Comment by bobylito** [comment]
https://github.com/algolia/algolia-ui-kit/blob/e25a3abed48863764f7a8e6dcfcfa222e120d2dd/samples/ecommerce/index.html#L26-L30

**Comment by bobylito** [comment]
So far we didn't care about car about html semantics, so why care now??

**Comment by redox** [comment]
That's fine no need to care that much; that being said I would go for `<div />` options inside the selector as well, it sounds a bit strange. What do you think?

**Comment by bobylito** [comment]
All divs seems consistent to me
